### ISSUE TITLE
Don't work without localized files

### ISSUE THREAD

**Issue by alexgearbox** [kvormweg/admnote#1]
Hi! Thank you for your plugin.

I have DokuWiki ver. Greebo, and it's don't work without localized files.

> Warning: require(/..path../lib/plugins/admnote/lang/ru/lang.php): failed to open stream: No such file or directory in /..path../lib/plugins/admnote/syntax/renderer.php on line 78 

https://github.com/kvormweg/admnote/blob/1a6ad62806a106fe7cb38eb24041e0597c51ffef/syntax/renderer.php#L78

You need to switch to the English language pack if the plugin doesn't have the language pack used in the wiki.

The plugin works well for me after adding the Russian language pack.

**Comment by kvormweg** [comment]
This bug should be fixed with the current release - if the language file for the current language is not available the English language file is used.
